on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Pull latest into wordle-project
        shell: cmd
        working-directory: C:\Users\23-017284\Desktop\wordle_cicd_m\wordle-project
        run: |
          git fetch origin
          git reset --hard origin/main
